---
# tasks file for prometheus-jmx

- name: prometheus jmx | create directories
  become: yes
  file:
    path: "{{ item }}"
    recurse: yes
    state: directory
  with_items:
  - /opt/prometheus/jars
  - /etc/prometheus

- name: prometheus jmx | download jar
  become: yes
  get_url:
    url: https://repo1.maven.org/maven2/io/prometheus/jmx/jmx_prometheus_javaagent/{{ prometheus_jmx_version }}/jmx_prometheus_javaagent-{{ prometheus_jmx_version }}.jar
    checksum: "sha256:{{ prometheus_jmx_sha256 }}"
    dest: /opt/prometheus/jars/jmx_prometheus_javaagent-{{ prometheus_jmx_version }}.jar
    force: no

- name: prometheus jmx | symlink jar
  become: yes
  file:
    src: /opt/prometheus/jars/jmx_prometheus_javaagent-{{ prometheus_jmx_version }}.jar
    path: /opt/prometheus/jars/jmx_prometheus_javaagent.jar
    force: yes
    state: link

- name: prometheus jmx | configuration file
  become: yes
  copy:
    dest: /etc/prometheus/jmx-default-config.yml
    force: yes
    src: etc-prometheus-jmx-default-config.yml
