---
# tasks file for prometheus-jmx

- name: prometheus jmx | create directories
  become: yes
  file:
    path: "{{ item }}"
    recurse: yes
    state: directory
  with_items:
  - /opt/prometheus/jars
  - /etc/prometheus

- name: prometheus jmx | download jar
  become: yes
  get_url:
    url: https://repo1.maven.org/maven2/io/prometheus/jmx/jmx_prometheus_javaagent/0.10/jmx_prometheus_javaagent-0.10.jar
    checksum: "sha256:b144a5a22fc9ee62d8d198f0dcc622f851c77cf52fee4bd529afbc266af37e29"
    dest: /opt/prometheus/jars/jmx_prometheus_javaagent-0.10.jar
    force: no

- name: prometheus jmx | symlink jar
  become: yes
  file:
    src: /opt/prometheus/jars/jmx_prometheus_javaagent-0.10.jar
    path: /opt/prometheus/jars/jmx_prometheus_javaagent.jar
    force: yes
    state: link

- name: prometheus jmx | configuration file
  become: yes
  copy:
    dest: /etc/prometheus/jmx-default-config.yml
    force: yes
    src: etc-prometheus-jmx-default-config.yml
