---
# tasks file for prometheus-jmx

- name: prometheus jmx | create directories
  become: yes
  file:
    path: "{{ item }}"
    recurse: yes
    state: directory
  with_items:
  - /opt/prometheus/jars
  - /etc/prometheus

- name: prometheus jmx | download jar
  become: yes
  get_url:
    url: http://users.openmicroscopy.org.uk/~spli/idr/jmx_exporter/jmx_prometheus_javaagent-0.10-SNAPSHOT.jar
    checksum: "sha256:48e2a9a5fc8e9f272981e5ec23f433e08a5abc4141ef568d2db6af34618a4265"
    dest: /opt/prometheus/jars/jmx_prometheus_javaagent-0.10-SNAPSHOT.jar
    force: no

- name: prometheus jmx | symlink jar
  become: yes
  file:
    src: /opt/prometheus/jars/jmx_prometheus_javaagent-0.10-SNAPSHOT.jar
    path: /opt/prometheus/jars/jmx_prometheus_javaagent.jar
    force: yes
    state: link

- name: prometheus jmx | configuration file
  become: yes
  copy:
    dest: /etc/prometheus/jmx-default-config.yml
    force: yes
    src: etc-prometheus-jmx-default-config.yml
